version: '3.8'

services:
  frontend:
    image: ${DOCKER_USERNAME}/air-core-dev-fe-images:latest
    container_name: air-fe
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - air-network
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  air-network:
    external: true
