name: PNPM Build and Deploy

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/air-core-dev-fe-images
  VITE_PUBLIC_MAPBOX_KEY: ${{ secrets.VITE_PUBLIC_MAPBOX_KEY }}
  VITE_VAPID_PUBLIC_KEY: ${{ secrets.VITE_VAPID_PUBLIC_KEY }}
  VITE_PUBLIC_API_URL: ${{ secrets.VITE_PUBLIC_API_URL }}

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/air-core-dev-fe-images:latest
          build-args: |
            VITE_PUBLIC_MAPBOX_KEY=${{ env.VITE_PUBLIC_MAPBOX_KEY }}
            VITE_VAPID_PUBLIC_KEY=${{ env.VITE_VAPID_PUBLIC_KEY }}
            VITE_PUBLIC_API_URL=${{ env.VITE_PUBLIC_API_URL }}

  deploy:
    name: Deploy to GCE
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to GCE via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USER }}
          key: ${{ secrets.GCE_SSH_KEY }}
          script: |
            cd /home/ubuntu/rowing/react
            docker compose down || true
            docker compose pull
            docker compose up -d
            docker compose ps
